REGISTER_URL = "https://stellarburgers.education-services.ru/register"
MAIN_URL = "https://stellarburgers.education-services.ru/"
LOGIN_URL = "https://stellarburgers.education-services.ru/login"
FORGOT_PASSWORD_URL = "https://stellarburgers.education-services.ru/forgot-password"
ACCOUNT_PROFILE_URL = "https://stellarburgers.education-services.ru/account/profile"
